#!/usr/bin/env python3
"""Generate and compile a wide Serde struct for the Windows MSVC target."""

import argparse
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "src" / "lib.rs"
TARGET = "x86_64-pc-windows-msvc"
DEFAULT_COUNTS = [16, 32, 64, 96, 128]


def generate(count: int) -> None:
    fields = "\n".join(f"    pub field_{index:04}: String," for index in range(count))
    SOURCE.write_text(
        f"""// Generated by repro.py. Run `python3 repro.py <field-count>`.

#[derive(serde::Deserialize)]
pub struct Wide {{
{fields}
}}

#[inline(never)]
pub fn parse(input: &str) -> Result<Wide, serde_json::Error> {{
    serde_json::from_str(input)
}}
"""
    )


def build() -> float:
    started = time.perf_counter()
    subprocess.run(
        [
            "cargo",
            "build",
            "--quiet",
            "--release",
            "--target",
            TARGET,
            "--lib",
        ],
        cwd=ROOT,
        check=True,
    )
    return time.perf_counter() - started


def benchmark(counts: list[int]) -> None:
    # Populate the target directory with dependencies before timing this crate.
    generate(1)
    build()

    print("| fields | wall time |")
    print("| ---: | ---: |")
    try:
        for count in counts:
            generate(count)
            elapsed = build()
            print(f"| {count} | {elapsed:.3f} s |", flush=True)
    finally:
        generate(128)


parser = argparse.ArgumentParser()
parser.add_argument("fields", nargs="?", type=int, default=128)
parser.add_argument(
    "--bench",
    nargs="*",
    type=int,
    metavar="N",
    help="time several field counts (defaults to 16 32 64 96 128)",
)
args = parser.parse_args()

if args.bench is not None:
    benchmark(args.bench or DEFAULT_COUNTS)
else:
    if args.fields < 1:
        parser.error("field count must be positive")
    generate(args.fields)
    print(f"generated {args.fields} fields in {SOURCE.relative_to(ROOT)}")
